### ISSUE TITLE
Using createinstallmedia from an apple script in catalina has problems

### ISSUE THREAD

**Issue by ITzTravelInTime** [chris1111/Create-Install-Media#1]
Hi, i just opened this issue to let you know that when SIP is enabled on catalina the "with administrator privileges" apple script is more restricted than in older version, this means that when createinstallmedia will fail because it could attempt to do some unlowed operations, i have experienced this with TINU which uses a similar mechanism to run the createinstallmedia as root, so i strongly reccomend to you to test your script on Catalina with SIP enabled and see if it works, if you  have problems and/or find any solutions let me know, currently i am studying what i can do to workaround it.

**Comment by chris1111** [comment]
I have already test on my real MacBook Pro that's why  I advise people 
**Disable the security SIP** and Gatekeeper on your Mac

This is the same on Hackintosh machine

Thanks
